export const BOOKS_AMOUNT = 9;

export const ADD_CARDS_REQUESTED = 'ADD_CARDS_REQUESTED';
export const ADD_CARDS_SUCCEEDED = 'ADD_CARDS_SUCCEEDED';
export const ADD_CARDS_FAILED = 'ADD_CARDS_FAILED';
